add missing step & fix path in Readme "To get started"
* Fix an error when setting up for the first time and running `npm run bootstrap` without first running `npm install`. 

> lerna ERR! ENOLERNA `lerna.json` does not exist, have you run `lerna init`?

* Correct path into demo folder
* Fix similar missing package error when running demo without first running npm install:

> Error: Unable to find plugin "gatsby-tinacms-json". Perhaps you need to install its package?